apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-ratelimit
spec:
  rateLimit:
    average: {{ .Values.rateLimit.average }}
    burst: {{ .Values.rateLimit.burst }}
