apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  annotations:
    tailscale.com/tailnet-fqdn: {{ .Values.tailscaleFQDN }}
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
