opentelemetry-collector:
  mode: daemonset

  image:
    repository: otel/opentelemetry-collector-k8s

  presets:
    logsCollection:
      enabled: true
    kubernetesAttributes:
      enabled: true

  extraEnvs:
    - name: CLICKSTACK_INGESTION_KEY
      valueFrom:
        secretKeyRef:
          name: clickstack-ingestion-key
          key: token

  ports:
    otlp:
      enabled: false
    otlp-http:
      enabled: false
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false

  config:
    exporters:
      otlp_http/clickstack:
        endpoint: http://clickstack-otel-collector.clickstack.svc.cluster.local:4318
        headers:
          authorization: ${env:CLICKSTACK_INGESTION_KEY}
    service:
      pipelines:
        logs:
          exporters: [otlp_http/clickstack]

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
