---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flux-auth
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCmOF87EOHT7LtArYOh9BopEvjoUwFAIC/NRKhjyyOFdXSqSDhxf2jNWmBcCllDF0x66j+bqSPrhNann2eWdhKRbTJTGPpNYO+4rpyP3x1VYlUeGNjIz3+pciY7PyBdmOodbIK1wvQAuBrvZJQqpjURxpM57s0RqteuH07VnPuBx/kHjZpsan9k6BISt3c7oGE1RElDNGnGOnH0qeuWo9eZYAiwhujmVKDCwSibVfeQbRoVfnAgMe1am3JJTpW4mxJF2rwqcvXOAWdNYsBQVPLVaHgASnSwsz4RTtZgVOVO8w/3YCazf/su8fAiC0UDspsbh3nSAy9BSWPfriz1oz8Jp92V5v+GOXUYA6PbU2/JRWrHZU8YVE6cZtKl8vHqpBOvz9J+JTIg0K39aPWrQtAfKucPaMlwyIVnJEskVsrkKAAWFCCguaP6LrlupJTpQ4JmGPxpzTfAwGYmlPcXO3/nEkTAffUEEPd7GYM91UM3Iobyp8srR8ifHIpnoIr3/Z3M5RxZofFq8G0Lw6APi4O5mSN9vA1P3w+SqYzezlTBqDtgQOFT8GdL3t+PHSJ9zfGS/3NUtCkLRjqZzFtoE0Bint8jBeKEWj9TJ4FaWcDifqTDbyJIjUhLAnlB2PO4PRfBh2/LEwlKbbMVo1U9DV370XZggEcEUNojdaIRBC7Cgwt/xKJsKNG4xVwPYHpdzJ9a0gd5pXcu+GdkneJawGoOP31Flw6pv8+TyRLudqZwBL1xEW3AwXNtogWTRjDaJ2N0vbhLGLxST5FQtKfACzWshZMTkxaNBqMhTeKmtk64RK0l/MbggTZFKUYE68S/m9l5Yno8ra+7h8EJStDnvKgOUJzHTXtjqAkrOyN+afw7OU64wJEP3najxqehGrFrkeUo8BnsduUEJ0GwdfZdgMJRbR9lm+yEAC++0tIvLV63ATpnwKB//ORJ7wMMVpebDQrT1GkT4hS5RvJH8Td1MXPYrXY79D/N7zrXDOd5DSE=
  template:
    metadata:
      creationTimestamp: null
      name: flux-auth
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
