apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-set
  namespace: flux-system
spec:
  interval: 30m
  releaseName: arc-runner-set
  targetNamespace: arc-runners
  storageNamespace: arc-runners
  dependsOn:
    - name: arc
    - name: secrets-operator
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: ./chart/gha-runner/gha-runner-scale-set
      reconcileStrategy: Revision
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: infra
        namespace: flux-system
