apiVersion: v2
name: rook-ceph
description: A Helm chart for the Rook Ceph operator
annotations:
  releaseName: rook-ceph
  namespace: rook-ceph

type: application

version: 0.1.0

dependencies:
  - name: rook-ceph
    version: v1.20.6
    repository: https://charts.rook.io/release
