---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgCFwReYd4E4Q9dO0eW+HRjcxoChG5bYrPBbRyfCuwp4AMGMUvbunrsoO7I4dXULEjmcnfUj/QceAX7U83Do5CaSnz99Sv0CnHLfIgMsg1ns21eaFMBFhp8lsSGWuEUvJX0G+ron/K+XsdbNdJInzEniUVc7NGOs9bOP12jl1T5sJY+gioRACIRXK8Nj4R+NLqgwYIYuEk+9Ak9uqZWTIaPCtf2g7zHmQiiiWAx51xn/15jdpqeJrqRTruF+ddf6MuYc4FiKHC09VyHC43lLdtx3pAw5BgR5a/101hG8Bzl9aIMKg48W41jJOVJt0PjOC6JDyqnisK4KuC0eybaMyopNh/ojVIUrgHD8acAdta1QFqAnDQ2RXnFRHNPOp6MUJstIwqpfSlWGQFnE9Nu9cbFydSksxdKvw/VSW9oTHALJdu+vcDG1K7qMXGkthYe3sOvAl5ZqRjwDZ6MhOnOUSG2/YuX9t3Jg3xz7PtJfozfKx+iNGMvNHRbEFgX0GLiyzyqmQcCX0w7oMXbSjprSyvWXkKne2FuQRpMSSrdihLrSY8VdaCy2TpDM7yQZkuAPMEWj/F+83s7xpbkZAmJzDwDi/R9ffRN5aeOfbARxOpjE1p9CrGn+rikR2VaDUtNFPwefkq+LFohajH+th7/V7oxguv2XPkC8A19NnuaMnyspGhiLBsn902NUY3v/6r1pdyo=
    runner-token: AgBXodz+Er+HyCh6o0Whgb352zuyH+F0v9tJq+LDJPQocys0eFuFv7Reza/hQyfNYGnGmzvyWge4hX2ef/NGCDNvxii/ivWVj+ATDHeyCbeEg1rah7Jzrm5gYvC/vIcbyxNph8s2HLp6p0q+11+wDzYK0W4oGJJR5Clh43rMbsKxSDPVWKADoO9wv1pUwkj5qWrqN+pkw7Nox+dNsem+fJ76YjY+QeK7RkuZtiD4K1arLrQvGdka2fwE6SYhu8N1+r/3cwlJd2sxOnfI9OFY3S++eg5FFhYPSxvFLaGXg/Y1L8Tek2uMgN06DMqLwMuAEsWivIX6N37wLMaC9av1lFU5Zvk0WX+3TJJkBJhfTLNfFnVscwXqgySJ5bsXbj94ALi+c6xSUZGK20p1uaP3pa00YQMixIhlYdfDLdOzZAFDLXfD9EgWS0f+N+oA9/MLeKdBK+n82/0BBwPg2e8Nf3VdBbczLF31ghQIMQStQkTj/d8I/HFU5LJ2dRPCQtq34c+d3DEKvlXybrPru6sglaVHIWScd0WuRx3yaLhvQLWra0DH5BgerYw/TVwyEOuXIzNlxEjNmEFJgs34Cc2C7LRC6fQtaAnzLExCiQg1V5W0kcbiBWkPpOl0E3uumY4i72uh9VLjQet1+o2AQR0sBt5s+uteZNcaBKyadOvMLneR2fGjcZXTC1yAAgQ3POYaSO2cTL0l0buBNxMGDchrt3uoS6C5eSQwky71jcYPUZsgyc71quUdf/4Ul8I4bHY9Q6QsNtSaDs9qqTq/32tfNSDIDqK3bK9i87bSyi4ndsI=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner
      namespace: gitlab-runner
    type: Opaque
