apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clickhouse-udf
data:
  laya_function.yaml: |
    {{- tpl (.Files.Get "udf/laya_function.yaml") . | nindent 4 }}
  laya.sh: |
    {{- tpl (.Files.Get "udf/laya.sh") . | nindent 4 }}
