---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  creationTimestamp: null
  name: r2-credentials
  namespace: vaultwarden
spec:
  encryptedData:
    ACCESS_KEY_ID: AgACClvsftPTuVFsuxg5EHWmFHHpDvK+SR5MNqXrehRKCkiqeKCvdgJM0MhB2q1XivQgWd6vvsyzcYIiAblJqbjEksvU0/D4jHjyNRdHGRv9OQYdRzWURW1r6A3WQKvv27BaRCvg4r642VsBMJOsnzvo1PPlLe32FTCmOuVdkEvobvCRrrXWZrTzFsb7tKuQR0Sb1t/vq8kENZ0W4DLln4Ov6STc8QdNQnnDjEfmwL8/Uj5DQJcwvD3Nw2LwqUe7+toeLZvWdcyg8bPRhXZ0o7hz2U9g0+9kT0xIonRdC2cptNkyuoWNkTlTwJijcj7mGiCFUCcDihnHl8CKoGN250mV6gD2WZHwBYOFHUB+hqHUh77X0PfYY/gIp/0Eu3NM1GC2/yMrErRzpGkhPeItjqJTgw5JretuX5Ocd3Ji6vh81pI4zKsBAVJyZ9/f6OXtVvlZPJt4ZCoXIniLBXUv5W7R+kGTs3DCzJcrkcAt0pTOZnIvG24xp2PNRzMjpIQ/bXaJ4ZXEvZNlb26fEBJU05ZPAm0pJngFO3XIjDTHVkEOAwx6ee8VUS5O/vqxa/621bzrB2M0wMtn0tBr9X9IYSj9DYfq/cx4znp3AD66p9CzBN4Ktlk46EHT7GpXnKeAJvjy2mIczRIDRCDFl9eJxtCu0QMPpGo9as9/4srNw5OtCWPrwIcLGcP/16V4+jjg4GypfqFQ09ZWsfg72F/bpe/CVrX47FNLALKyK/pTWMCupw==
    SECRET_ACCESS_KEY: AgB679/hSO3IxIf3FYzG892/fnzh2yZ4+amSvHa3rXmapKcnrEDrbFevUfTyz6LnvD4qYLnyvPhN6reUygaretUwq+Km7/O+JOmNuKamOIu67QrptglWWAtRppnE69cXb+ghLwwCdrxGcwN4A+6DmtZVwDlwMZEj/6xFBoJ2iDJlRkeI0kSx+LAOzumsFN6Aq7IspJAinWYcxc/P2f99V+utKRIYWMSeWZeObfWrdOo2W0agNFoHA7JYMTMmnO9MHsI0m/voe4Ls9QfeWxDU5NiNzxHwIK/grqMbms27NGLDkZK+gTxvdCeMeFOD58U0/Nlx/dPkAV7ei54LawfNitInt70U+B0HfIN13/yV2iALVmvq8F9D5eUycP1mVQ5W4m3uuqBiSz/sPqCaR0GrwqmOmHfk/m+CuU/1KXT9YgRm0TrUjiyg9WehnrkkqqpCv2a1iUXmm0oKYFGWb9eFdV9uDYo5n6/hFG7YU9VuEgoaCBsq9+V+NdkjR8ELC5H7hhP110qeFWEYL03JPJ/QIyOMOXYMP1vo0kpz8BbNBun5eYhBSDT+3NFGtTmq0se/Z4OSGdnO9njNQ4y4u5KwKXfjJ68l8x7vo6VLj++HALXhgy8e5xQdnHevQs25AS/f5gEYoxD1pNYPUnT+BjYQd1tDUnSyXxQ5ex82zO8Ou56VGxZ3H1yWmmGT4f6pcvZV0R+0KD6ywNWzWEk2gdoZmC6JXRNzFTU1GnH8LGdbwBfVox+gLGt2Ks76qS0XwSCt+LDS2NtZB/8CqKjsVmzHaEO6
  template:
    metadata:
      creationTimestamp: null
      name: r2-credentials
      namespace: vaultwarden
