---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgAwqBERsdCmItO08wvH0210s2lv88ZGqdQac/SScZK3m0TIhE0adriLmzEpJI6I6E6IqJSDfU7Cu33lR6cDD4LMC2Pw3uECNUQKn2rruMpz2R6K1LAcXWCwtBADUlG8qyPZ854QIEjzNSB6BDqlVN58E/WtiYe/42VhARe1WZyOCkvp0xhSVVpzzzenVLIHrdo3ETeaFz69WtS5iE4WiF2DjiczoUTv75XHpyCU+S0Od/KentkS4TTYrziXwou86G2zoA6/MojxmeCi9blXZ50/EOrpgyvVtGUL07b0PWOMSBTdaYPvMCKfglb/InqiASkK1iEhJsoXFGeju+Va0OpdtFFHaS6TIUGM30zBhPBES3+bddjfGXZ9MnOJbovw69iEgJcvY7v9Fdxi0h6rEHh6gjI6zhnESrlKaQMYNMugGE6kIHQJZyCKUg2v5iSWOuyiOyAhy8HOqAeJ56MgwgJJZth5CZIQ9NO9xN1VbfWGEp2OL23eM/GPW7TCfJrx3a6kZmJezAiNJyUuX7v+aEWGPy73BvDfsGxQnrrDWOltxsr4rxQJAiAQSFNzw74lTz/Vf0FsGWQ40qNjYysgFDanHxV+QFyvazkBRSW6G3baAf+c9FwrroD4KzXJ7sdOVJ35ynD6Km0AoxRB6by7Hr43Topya4670trI3Ycu6mZK+j1KJ9Wz1IkwE+ILP8lufidlVVUxzqpFl6p2n1PAm40gLhCOup2LG7FrQoK7WJ1ibz542Add6I2TkQOJwrFPMzT+6tDt7gGbNqOo1B+/1dJYTAaisVgFGZd4K5+ALYbDE4crtYa2dD0B1n5yacsJU7GbjUXEfWQmQeZFwfNGHiPhY0YrvNmO
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin
      namespace: vaultwarden
