---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-smtp
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgBNTz0MAwiRGxiRNx3k/ZvUmGeNxeNQ3Cy7RYDbOubNG36kiVTHFrtMOvFgOOwBM+mz+yH+SuGMFmBMrso0r6pZxeM/fmp1MfjKHYxfqHvXJxHKHIJIsN84OivvtW0+Mru+ugjQF2706HDMrYlk5troQ8Me0pnXIAEoh3yuru/qjSACBvuiKjzAbICIVmLaCKYh7wIYsRbMeWxtMBLxGc0O/z88m9Ee2E5/TrHI2CsM/Bi6Lr+ZtGazY3oLU05T+EFJMGuY9h1PMG6mNOOhYsSsNe3bx+30dkxd+UP6Nt9GKxaUti2G9YFE4jP3mIJr21qGjLvagYQepqzbyJe7/Jtztuka1COhQIKkhQbxeQewY3az1/EbiB5pKTA99IKdEm7MCqMwdhmIlbJnnQLv7N5JXJvn+EDGf8bKqYVtWRG+u+9VIu+1iCr1I8XvtmxorCe8Fmr9iKvKqsESDrAORr8wPsVUPKffV5KqPoEsnzqC+RtBEBJIkGz7ExxAAEpBPKMJZgsQwGmm2skGGTyGSJVA2Lh6cWcTUvFDva7q4xbyA+CkNaYwGP6yoMVkRfnFIPydFaNdIuNFw8evE2d7lpJwoz4LiMsuRcn6qhnOf/C3GhegUOMFIQkjB20sO69C7UbYl2hN9DCT7epW7Szzrw9msWh+HTmsAYCfqzHh9w4QPTTOuxU3o5O89oJHePnzey03LHnFZaovHXlfaPXh+Us42D/fH/81m2SMiPY7uuFdrz4uU1MoWV8XVBIk4BZplOHpRw==
    SMTP_USERNAME: AgAupEnnS++rG3TE2Miq90hFhzOQWGnyrD7iiIzpLlVOOL05DfixuoVNPxDH4FK9ynrojkFE87fSB6/J6PbbMSTOsHojOlfdT6AXMcnS1NjcEKTGWokK9V3nkizOF+tdzGDsyW31feQSQlTBiY/LYTvA6dj4DL4uyfJgabOI7Mjob9m06qKKu7bCfFHHtfj2kMExweqh7Su0+tqLzGjsaiMwnzypWf88R0o4KzSaZN8hC/IKbrFCJzXgHmtaH+IE0jj4yrpKJf8EA8o8RAJyq+VFQJhRy27JeiHCQ/0yh3QuJeb5tVwXhuk25gPrt7jMGPbkNj2OOKP86hLbiB5NhCGJGCxY78fvMfgvCdohPVjMp27Ivy516KqqAMMO+fYlomWe4902KCRUcVbk3IhOGWq4rUfoQgzaqTs1RiD6rEC701Txe/tK0x63O8qeY/ywPpOErdrTO9D3Oz3B9Cq5grPgZjnQk8Ee/HubdvaRmiRvbDZcDxCanT3VPasRuvCzEIsCQ9uTq2+cf78FeReDfOii4KSpo80y21frxcqyVQ3jZj9zx+xCECIoIBgswFqpYnWIt328G/7YKJsZVxR/RYe1vDmGmi/fXmN+VIDYXA+3fXTk57DbSjB12uidYeldXzEe935uWz4BrrsQzxStcpM/Y953t0osrqzSNA2DQEW+vCpxg/iJoM4FkwWwWfLuNvt3VzrAbuBsUTW0R9frcF/v
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-smtp
      namespace: vaultwarden
