apiVersion: v2
name: gha-runner-scale-set-controller
description: A Helm chart for actions-runner-controller

type: application

version: 0.1.0

dependencies:
  - name: gha-runner-scale-set-controller
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
