---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghr-github-token
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgBPFBYI0xt2ORbPww/JvQ4p+DxALFmOgpMUXopv9wpu1/TUWiNb7elbG0uGvwnbaVei4J4vb9Gi4W3zgBm5/uqpDYixm56CZOT1h2pPSRpmMf4Z51bqxMzjqi58nkmI/WrvUw+C26y2zt5z4Oub+oy2ToU+fLMvF9mROHCWslLAplejh1nd54am1x+xaZunR2frHxguVPi+ZJEpRjJId3xWJZhy0/8eMbmrAmQSS9JJpVwWA785mT8K82Zya7UTAE5ecJ4d2gSIttFkdKhlT3ZAQyT62wj6ZCt+Vhf2kg6TG/xrGlYDRosdpreOLNyW4+5By7jbMRMwiGBr8EBPLi8AHV/7oVu9s7o3fC+O/4omKTssIYU1nisFxBRB4xpzKzmfSxBnSSjYclRa2bAaqczlGtCj/L+oLuxq/2OWx6r5xQ9xqrKNYrDYHzNQtzlTLRVgcbbWZGTvcPHraSX/tJ7wIVbP4ManZIZOu8TPTPgS+NByq3hhWiTBUKKCGUkSnRe13P5+h2405x3tNbg3z1i95oxXZWUZ84gtvW/ggw9WmDtM334tNnoP+L/VW14ANg5hgjPbIfiKnDFfO/O9bVnYsBoUFtIbYuF4w1N1WHIr0FpjIirsADDVyw7FuPH088ZRiFuUaIsEhZvdF5VBa76NL31W72/qREPUpNfkREafYMntIwfAR5LKH58FyYde46aTcCuCw0GYMm46Kj1Bbx1n7zH7K/O2PZvYMHzjvBqDXPOxpfte0mW4
  template:
    metadata:
      creationTimestamp: null
      name: ghr-github-token
      namespace: arc-runners
    type: Opaque
