---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickstack-ingestion-key
  namespace: otel-agent
spec:
  encryptedData:
    token: AgBPChr5UBMxRteiVlbzV/JKtXu5zIA8qiJx1pvmigIG72CpG585LzyWrQWYP08No1zjcHW+SUhUT82GjJVOAmzB+IsFxIVCR6+nXbNkV9v/5nOfyReffPEU/+VBFO8Y1+kUtTeDfofyXG2ya/Jti0ODaQ6P4r+PpSM71aaTTMUzXMxs4eJ/qF5gHYhyVEALDhjRQIo0oCAst4+aTu3eHe+XtSptNNAphQHTJjU3sUregExVNWhsa2FxuOVweucWk0lwBvdrFuXrhrIK9d8XX1hoxI81TajWbkn7NdQyJx3yvzB05eTlU1XkHAke3XwAXvvA8oxL6Bgyo90vjyqHkR/kesDsaXGmVG2SPiUc8Di8ea9P6ufKgIQ9lUZt4GvRZVVphXfpULPyW9Bye/KjPhiQCvqhTOWvtITuK324CRuq5kAiLKS12tnUl9ZcIvnrXpx/fYiFHXzzbMpwVZcv3FxbivkWlIcKOqZgJ401tgWLqFcWyPjUP1Z0T6OUdNRR6hyJS3fLImx9YlhZME5ZKBs0fZzzuLIkhP0G4K1nst1hUP3heAmUUvb8LGndyWEkGN++qN2zus1T1N5OQCF7CPQwoTsRaAgC/4kTsZXM50JJP0g2xCvk9tNJeMw0r2oKHR6AQrR02OA76DaaN9t8DS9tRjcfRbfzGc66Wl0suFo1x7QbJmnn8WAa6euXWplxxs/iK3PaCslQ5cwQdUmsWtKsJTKAyivw6EZmqFFCTy3PI+uJLDM=
  template:
    metadata:
      creationTimestamp: null
      name: clickstack-ingestion-key
      namespace: otel-agent
