---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCCGFaIFX6qSltJSfmzGMSqRfDEIzmRrWBqwUymIT6Y7bhtlygCqHsp6c0j4O9ySPjeJlnIGi/QhB7bk/MGNJzFDs9G7KPYkuf1jMrf92aPGUz/Kwa7S4puJ9+KvuG8YcJNfvH4+nqn5zNxBpgu7fL6YeVASyQFHqdN45FfaQtcaZCKau5VMkLQrNoC4DzMdk+L8ClQ1yfL3qbL7s1gMwX4hZwHURnb6CfYPTSsY4/Ukg5mukMAspHb9NsqtZRSyX9MSDKXweBUDFwsw2RWi+VFEs3aFKIT2VxKmtsPxohC88HDwFcIKk+polNvGhAxUbl1g8161lw6RCGA7y6emTqli4e0dOsBXbi10Af+T7Ilj4hJvH7xEm0uvdGcbYERT/VnzBEyXD0cqjL0Ys1NNFs1SKuinMWekhUCAG618hKZwopePGx+iI/4KCZ4yy+KT0J5xbjTEv+QwNXhvPyRPzB3KntD4IkX9zX2dFcCnBLXrwZiZ9dq6WMH7qE8mS33rSooEFLmGHjhQZWChLdYiWyRjBaKM+ZFtknA1zTdj1+hu+vAW4m495oryGwzgp/sN/23QFBv71Vb/wXqWSuk1tVjJVlP5cclrcp/3uyEBSCDq+SBx8fshG2PXm/INJpC62nO1sjDAjE0ac6/Lhk63LvPf0K83NC5kGZPB9OF8Lcru2kbEJNw1T8X7OYd7gMeXFLVfBj4Jda0uS/F6rmIoaIvV+L7hAeC2qTQq/oW7H81YMzU3YsKmY9rU1jPLuKdDiws/6z/3A==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
