apiVersion: v2
name: ceph-csi-drivers
description: A Helm chart for the Ceph-CSI Driver CRs, service accounts and RBAC

type: application

version: 0.1.0

dependencies:
  - name: ceph-csi-drivers
    version: 1.0.4
    repository: https://ceph.github.io/ceph-csi-operator
